keyword = [
    # Français
    "je ne peux pas",
    "je ne peux pas vous aider",
    "je ne peux pas t'aider",
    "je ne suis pas en mesure",
    "je suis désolé",
    "désolé",
    "je ne peux malheureusement",
    "il n'est pas approprié",
    "ce n'est pas approprié",
    "je ne fournirai pas",
    "je refuse",
    "contraire à",
    "illégal",
    "illégales",
    "malveillant",
    "je ne peux pas répondre",
    "je ne vais pas",
    # Anglais
    "i cannot",
    "i can't",
    "i'm sorry",
    "i am sorry",
    "i cannot assist",
    "i can't help",
    "i'm not able",
    "i am unable",
    "i won't",
    "i will not",
    "it is not appropriate",
    "against my",
    "i'm not able to provide",
    "as an ai",
]
